- name: Reload Django application
  hosts: myhosts
  tasks:
    - name: Updating code base
      ansible.builtin.git:
        accept_hostkey: true
        clone: yes
        update: yes
        name: git@github.com:nurads/adero.git
        dest: adero
        force: yes
    - name: Install Pip requirements
      ansible.builtin.pip:
        virtualenv: ~/adero/env
        requirements: ~/adero/requirements.txt
    - name: Migrate the database
      shell:
        chdir: ~/adero
        cmd: env/bin/python manage.py migrate
    - name: Collecting Static Files
      shell:
        chdir: ~/adero
        cmd: env/bin/python manage.py collectstatic --no-input
    - name: Reload app Service
      become: true
      ansible.builtin.systemd_service:
        name: gunicorn
        state: reloaded
        enabled: true
    - name: Reload Nginx Service
      become: true
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
        enabled: true
        daemon_reload: true
